Qwen_Qwen2.5-32B$:
  loader: Transformers
  gpu_layers: 28
  cpu_moe: false
  threads: 16
  threads_batch: 0
  batch_size: 1024
  ubatch_size: 1024
  ctx_size: 8192
  cache_type: fp16
  tensor_split: ''
  extra_flags: ''
  streaming_llm: false
  rope_freq_base: 1000000
  compress_pos_emb: 1
  row_split: false
  no_kv_offload: false
  no_mmap: false
  mlock: false
  numa: false
  model_draft: null
  draft_max: 4
  gpu_layers_draft: 256
  device_draft: ''
  ctx_size_draft: 0
  mmproj: None
  cpu_memory: 0
  gpu_split: ''
  alpha_value: 1
  compute_dtype: float16
  quant_type: nf4
  load_in_8bit: false
  load_in_4bit: true
  attn_implementation: sdpa
  cpu: false
  disk: false
  use_double_quant: true
  bf16: true
  no_use_fast: false
meta-llama-3.1-8b-instruct-q4_k_m.gguf$:
  loader: llama.cpp
  gpu_layers: 33
  cpu_moe: false
  threads: 32
  threads_batch: 5
  batch_size: 2048
  ubatch_size: 512
  ctx_size: 32768
  cache_type: fp16
  tensor_split: ''
  extra_flags: ''
  streaming_llm: false
  rope_freq_base: 500000
  compress_pos_emb: 1
  row_split: false
  no_kv_offload: false
  no_mmap: false
  mlock: false
  numa: false
  model_draft: null
  draft_max: 4
  gpu_layers_draft: 256
  device_draft: ''
  ctx_size_draft: 0
  mmproj: None
qwen2.5-14b-instruct-q4_k_m.gguf$:
  loader: llama.cpp
  gpu_layers: 40
  cpu_moe: false
  threads: 32
  threads_batch: 4
  batch_size: 2048
  ubatch_size: 512
  ctx_size: 8192
  cache_type: fp16
  tensor_split: ''
  extra_flags: ''
  streaming_llm: false
  rope_freq_base: 1000000
  compress_pos_emb: 1
  row_split: false
  no_kv_offload: false
  no_mmap: false
  mlock: false
  numa: false
  model_draft: null
  draft_max: 4
  gpu_layers_draft: 256
  device_draft: ''
  ctx_size_draft: 0
  mmproj: None
